spring:
  application:
    name: ${SPRING_APPLICATION_NAME:apc-backend-assignment}
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: false

management:
  server:
    port: 9081
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus, beans
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: diskspace,mail,db
        liveness:
          include: diskspace,mail,livenessState,db

logging:
  level:
    nl:
      apc:
        legoland: TRACE

server:
  port: 8080
  servlet:
    contextPath: /apc-backend-assignment


info:
  build:
    name: @project.name@
    artifact: @project.artifactId@
    version: @project.version@
    groupId: @project.groupId@
    java:
      version: @java.version@